Improve docker
iamluc/docker-hostmanager pull request #38
Opened 2018-04-20 21:05 UTC by mykiwi

I was playing with your repo, so I made some updates:

- Optimize Docker image: 42.6MB into 20.3MB
- Optimize PHP autoloader
- Update PHP dependencies

2018-04-23 07:56 UTC, iamluc requested changes
Nice! Thank you.
Other than the entrypoint, LGTM :+1: 

But could you target the `develop` branch ? It will allows us to test it safely

2018-04-23 07:56 UTC, iamluc commented on Dockerfile
> +CMD ["/usr/local/src/docker-hostmanager/bin/docker-hostmanager"]
Not sure about changing the entrypoint... It will beak for users that have parameters/arguments

2018-04-23 08:08 UTC, mykiwi commented
Ok :smiley:

2018-04-28 15:14 UTC, mykiwi commented
Done :)

2018-05-08 05:56 UTC, merged

2018-05-08 05:56 UTC, iamluc commented
Thank you!